app:
  cache:
    size: 350
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/movie_land
      username: postgres
      password: 12345
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always

spring:
  flyway:
    baselineOnMigrate: true

nb:
  url: https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange

random: 3


